---
fail_fast: false

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-json
      - id: check-yaml
      - id: check-symlinks
      - id: double-quote-string-fixer
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]

  - repo: https://github.com/ansible-community/ansible-lint.git
    rev: v6.4.0
    hooks:
      - id: ansible-lint
        args: ['--profile', 'shared', '--warn-list', 'unnamed-task,schema[meta]']
