---
prerun: false
dependency:
  name: galaxy
  enabled: false
driver:
  name: lxd
platforms:
  - name: molecule-instance
    url: "${LXD_HOST:-unix:/var/snap/lxd/common/lxd/unix.socket}"
    source:
      alias: "${MOLECULE_DISTRO:-ubuntu/20.04}"
provisioner:
  name: ansible
  connection_options:
    ansible_lxd_remote: "${LXD_REMOTE:-local}"
verifier:
  name: ansible
